CREATE TABLE IF NOT EXISTS outdoors.biking(
   City                             VARCHAR(28) NOT NULL
  ,Street                           VARCHAR(83) NOT NULL
  ,State                            VARCHAR(3) NOT NULL
  ,Status                           VARCHAR(15) NOT NULL
  ,Year_completed_or_to_be_built    VARCHAR(11) NOT NULL
);
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Fairbanks','Airport Way','AK','built','unknown');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Huntsville','Spragins St NW (Monroe Street and Spring)','AL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Fayetteville','Van Asche Dr. (N. Gregg Ave. to Hwy 112)','AR','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Russellville','El Paso Avenue (phase 1: Parkway to L)','AR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Springdale','Silent Grove Rd (Silver Fox St. north to Wagon Wheel Rd)','AR','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Springdale','S. Powell St.(E Don Tyson Pkwy to E Robinson Ave)','AR','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Phoenix','N15th Avenue (W Van Buren and W Jefferson streets)','AZ','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tempe','Priest Dr (Washington to Van Buren st)','AZ','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tempe','S Hardy Dr (`w Howe St to W 16th S)','AZ','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tucson','St. Mary’s Road (between I-10 and Church Ave)','AZ','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tucson','Stone Ave (Toole Avenue to Alameda St)','AZ','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Alameda','Fernside Blvd','CA','built','2008');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Alameda','Alameda Shoreline Drive','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Berkeley','Bancroft Way (Dana St to Fulton St)','CA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Berkeley','Hearst Avenue','CA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Carpenteria','Via Real (Casitas Pass Rd. and Vallecito Rd)','CA','built','1970');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Davis','J Street ( near Drexel Dr.)','CA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Emeryville','Christie Ave (Powell Street to Shellmound St)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Long Beach','3rd Street','CA','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Long Beach','Broadway','CA','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Long Beach','Artesia Blvd (Atlantic Blvd to Orange Ave)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','Spring Street (1st to 9th St)','CA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','Riverside Drive Bridge','CA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','W 2nd St ( from Figueroa Street to Hill Street)','CA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','Reseda Blvd ( Plummer St. and Parthenia St.)','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','Los Angeles St (First St to Alameda St)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','Venice Boulevard (Inglewood Blvd. and Beethoven St)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Los Angeles','Van Nuys Blvd (Laurel Canyon Blvd to San Fernando Rd)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Modesto','College Ave (Briggsmore Ave and 9th St)','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Modesto','9th St (connecting the two campuses of Modesto Junior College)','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Mountain View','Castro Street (from El Camino Real to Miramonte)','CA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Mountain View','Shorebird Way at Shoreline Boulevard','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Oakland','Broadway (Keith Ave and Brookside Ave)','CA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Oakland','Telegraph Ave (20th to 29th st)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Oxnard','Ventura Rd.  (7th Str and 5th St)','CA','built','1970');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Palm Springs','N Belardo Road','CA','built','unknown');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Redondo Beach','Harbor Drive (Herondo St to Pacific Ave)','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Richmond','Shipyard 3 Trail','CA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Jacinto','Ramona Expressway (San Jacinto Ave and Main St)','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Jose','Sunset Ave (Story Road to Hopkins Drive)','CA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Jose','S 4th Street (San Fernando to San Carlos)','CA','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Jose','Curtner (Westgate to Shibley)','CA','built','before 1978');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Santa Barbara','Cota Street','CA','build','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Santa Cruz','Beach St (Bay St to 3rd St)','CA','built','2008');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Santa Cruz','West Cliff Dr','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Santa Monica','Pico Boulevard (7th and 6th st)','CA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Santa Monica','Colorado Esplanade Ave (5th Street to the Santa Monica Pier)','CA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Temple City','Rosemead Blvd','CA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Market Street (12th Street to 8th Street)','CA','Built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Portola Drive (Burnett Avenue to Twin Peaks Blvd)','CA','Built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Laguna Honda Blvd (Clarendon Avenue to Plaza Street)','CA','Built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Alemany Blvd (Rousseau Street to Crescent Avenue)','CA','Built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','John Muir Drive (Skyline Boulevard to Lake Merced Boulevard)','CA','Built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','JFK Drive (Kezar Drive to Stow Lake Drive)','CA','Built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Duboce Avenue (Church Street to Fillmore Street)','CA','Built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Cesar Chavez Street (Kansas Street to Mississippi Street)','CA','Built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Cargo Way (Amador Street to Jennings Street)','CA','Built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Point Lobos Avenue (Merrie Way to Balboa Street)','CA','Built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','San Jose Avenue (Monterey Blvd to Saint Marys Avenue)','CA','Built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Polk Street (Grove Street to Market Street)','CA','Built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Market Street (Octavia Street to Pearl Street)','CA','Built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Bayshore Blvd (Industrial Street to Paul Avenue)','CA','Built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Oak Street (Baker Street to Scott Street)','CA','Built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Market Street (Gough Street to Franklin Street)','CA','Built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Fell Street (Baker Street to Scott Street)','CA','Built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','13th Street (Bryant Street to Folsom Street)','CA','Built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','JFK Drive (Kezar Drive to GGP Access Road)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Golden Gate Avenue (Jones Street to Market Street)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Folsom Street (2nd Street to Essex Street)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Folsom Street (13th Street to 12th Street)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Division Street (San Bruno Avenue to Vermont Street)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Division Street (Potrero Avenue to San Bruno Avenue)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Bay St (Fillmore Street to Laguna Street)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','17th Street (Kansas Street to Potrero Avenue)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','11th Street (Harrison Street to Bryant Street)','CA','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Division Street (Potrero Avenue to 11th Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Valencia Street (Cesar Chavez Street to Duncan Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','The Embarcadero (Bay Street to North Point Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','San Jose Avenue (Saint Marys Avenue to Randall Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Laguna Honda Blvd (7th Avenue to Clarendon Avenue)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Bosworth Street (Elk Street to Bosworth Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Bayshore Blvd (Flower Street to Cortland Avenue)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','8th Street (Stevenson Street to Harrison Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','7th Street (Stevenson Street to Cleveland Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','17th Street (Hampshire Street to Harrison Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','13th Street (Bryant Street to Folsom Street)','CA','Built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Francisco','Turk St (Mason and Polk streets)','CA','Built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Santa Ana','Bristol St (17th Street and Washington Boulevard)','CA','Built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Murrieta','Nighthawk Way (Washington to Hayes Ave)','CA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boulder','Broadway','CO','built','1980');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boulder','13th Street','CO','built','1992');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boulder','Baseline (30th-35th Streets)','CO','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boulder','University Ave.(9th Street and Broadway)','CO','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boulder','Folsom (Valmont Road to Spruce St)','CO','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','Bannock (14th to 15th)','CO','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','15th Street: Downtown','CO','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','Lawerence Street (Auraria Campus to 25th St)','CO','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','Arapahoe St. (Auraria Campus to 24th Street)','CO','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','Stout Street (19th to Downing)','CO','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','South Broadway (Bayaud and Virginia Ave)','CO','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','14th St (Market to Court Place)','CO','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','Wynkoop St (15th to 18th Streets)','CO','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denver','14th Ave (Speer Blvd to Bannock)','CO','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Fort Collins','Laurel St ( Howes St to College Ave)','CO','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New Haven','Long Wharf Drive','CT','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New Haven','Brewery St','CT','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','15th St NW (Mass to U)','DC','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','Pennsylvania Ave','DC','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','15th St NW (E/Pennsylvania to V)','DC','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','R St NE','DC','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','L St NW (12th to 22nd)','DC','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','M St NE (1st St to Delaware Ave)','DC','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','6th St NE – Florida Ave to Brentwood Pky','DC','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','1st St NE (Union Station to M St)','DC','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','M St NW (Thomas Circle (West) to 28th St)','DC','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','15th Street NW (V St. NW to W St NW )','DC','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','Jay St NE – Hayes St to Kenilworth Ter','DC','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','15th St NW – V St to Euclid St','DC','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','Hayes St NE – Jay St to Anacostia Ave','DC','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','4th St NE (M St to Morse St)','DC','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','6th St NE (M St to Florida Ave)','DC','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','M St NE (Delaware Ave to 4th St)','DC','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Washington','Maine Ave SW (7th St to 12th St)','DC','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('St. Georges','St. Georges Bridge','DE','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Miami','West Ave (Lincoln Rd and 17th St)','FL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('St Petersburg','1st Ave (Pinellas Trail)','FL','built','2008');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tallahassee','S Adams St (E Madison St to E Gaines St)','FL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tallahassee','Lindgren Ave','FL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tallahassee','West Madison St','FL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tallahassee','West Pensacola St (S Macomb St and S Duval St )','FL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tallahassee','St. Augustine St (S Macomb St and  Adams St)','FL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tampa','E Cass (Poe Garage to N Nebraska Ave)','FL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Winter Park','Cady Way (Cady Way Trail to Perth Lane)','FL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','W Peachtree Street (at 5th)','GA','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','10th (from Monroe to Charles Allen)','GA','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','Park Place (Edgewood to Auburn)','GA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','10th NE St (from Charles Allen Dr to Myrtle NE St)','GA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','Peachtree Center Ave (from Edgewood to Peachtree St.)','GA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','Westview Drive (Chicamauga to Lawton)','GA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','John Portman Boulevard ( Centennial Olympic Park Dr to Piedmont Ave)','GA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Atlanta','Luckie St (Georgia Tech campus south to Centennial Olympic Park)','GA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Honolulu','South Street (King St to Pokukaina St)','HI','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Honolulu','King Street (South St to Isenberg St)','HI','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cedar Rapids','3rd Ave (3rd St SE and 6th St SW.)','IA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Des Moines','E Grand Ave (7th to River)','IA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Waterloo','Park Avenue (South St. to Walnut St)','IA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Johnston','Northwest Beaver Dr','IA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Aurora','River St (North Ave and Downer St)','IL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Champaign','Lorado Taft Dr','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Champaign','S 6th Street','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Champaign','S 4th Street','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Champaign','E Armory','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Champaign','Peabody','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Champaign','S Wright','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Kinzie St (Milwaukee to Wells)','IL','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Jackson Blvd (Oakley to Ogden)','IL','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Jackson Blvd (Independence to Central Park)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Sacramento Blvd (19th to Ogden)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','18th St (Canal to Clark)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','55th (Cottage Grove to Dorchester)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Elston Ave (Milwaukee to North)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Franklin Blvd (Sacramento to Central Park)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Marshall Blvd (California to 19th)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Desplaines St  Harrison to Kinzie)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','31st St (Wells to Lakefron Trail)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Dearborn St (Polk to Kinzie)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Lake St (Central Park to Damen)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Milwaukee Ave (Kinzie to Ellston)','IL','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Harrison (Desplaines to Wabash)','IL','buit','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Lake (Laramie to Central Park)','IL','buit','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Clarendon Avenue (Irving Park Road to Broadway)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Milwaukee Ave (Elston to Augusta)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Roosevelt (Wabash to Indiana)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Sacramento Blvd (Ogden to Douglas)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Marshall Blvd (24th to 19th)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Washington (Wacker to Michigan)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Canal (Roosevelt to Harrison)','IL','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Halsted (26th to Van Buren)','IL','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','State St (26th to Cullerton)','IL','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Vincennes (103rd to Summit)','IL','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Broadway (Montrose to Wilson)','IL','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Clinton ( Jackson St to Fulton St)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Clybourn (Division to North Ave)','IL','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Clinton (Van Buren to Jackson)','IL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Elston (Elston Ct. to Fullerton)','IL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Randolph (Clinton to Michigan)','IL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Franklin Blvd (Central Park to Sacramento)','IL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Polk (Damen to Loomis)','IL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Loomis (Eleanor to Cermak)','IL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chicago','Loomis (Polk to Van Buren)','IL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Evanston','Church St (Chicago Ave to Dodge Ave)','IL','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Evanston','Davis St','IL','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Evanston','Dodge Ave (Howard St to Lake St)','IL','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Evanston','Chicago Ave (Grove St and the intersection of Chicago Ave and Sheridan Road)','IL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Evanston','Sheridan Road (Chicago Avenue to Lincoln Street)','IL','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Urbana','W Pennsylvnia','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Urbana','Springfield Ave','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Urbana','W Green','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Urbana','S Matthews','IL','built','1970s?');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','Shelby Street','IN','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','Indianapolis Cultural Trail','IN','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','Indianapolis Cultural Trail','IN','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','30th St (N White River Pkwy W Dr. to N Harding St)','IN','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','Keytsone Ave','IN','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','Pennsylvania St (St. Clair and Washington)','IN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','New York St (East Side)','IN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','North Arsenal Ave','IN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Indianapolis','Michigan St (IUPUI)','IN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('South Bend','South main street (W Marion to W Western Ave)','IN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Manhattan','N Manhattan Ave(between Moro St & Bluemont)','KS','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Louisville','S 4th St','KY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Louisville','S 6th St','KY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Western Ave','MA','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Mt. Vernon Street','MA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Beacon St (Massachusetts Ave and Charlesgate East)','MA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Massachusetts Ave (Harvard Bridge to Symphony)','MA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Staniford St','MA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Congress St','MA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Atlantic Ave','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Commercial St','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Causeway St','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Westland Ave (Hemenway to Edgerly Rd)','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Beacon St (Berkeley St to Mass Ave)','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Casey Arborway','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Boston','Beacon St (Miner St to Brookline Town Line)','MA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cambridge','Vassar St (Main to Mass)','MA','built','2004');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cambridge','Vassar St (Mass to Amesbury)','MA','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cambridge','Concord Ave (Alewife Brook Parkway to Blanchard Road)','MA','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cambridge','Ames Street (Main Street to Broadway)','MA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cambridge','Binney St (Land Boulevard to 3rd St)','MA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cambridge','Western Ave (Mass Ave to Mem Dr)','MA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Baltimore','Cromwell St. (West Covington Park to E. McComas St)','MD','build','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('North Bethesda','Nebel St (Randolph Road to Marinelli Road)','MD','build','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('White Flint (North Bethesda)','Woodglen Dr (Edson Lane to Nicholson Lane)','MD','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Detroit','East Warren','MI','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Detroit','Conner','MI','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Detroit','Cass Ave','MI','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Detroit','Michigan Ave (Livernois and Cass avenues)','MI','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Detroit','Livernois','MI','build','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Detroit','East Jefferson Ave (Alter Rd and Lakewood St)','MI','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Grand Rapids','State Street','MI','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Grand Rapids','Monroe Avenue (Guild and North Park streets)','MI','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','36th Street (Richfield Road and Dupont Avenue south)','MN','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Oak St SE (Washington Ave and East River Road)','MN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Plymouth Ave N (Lyndale to 8th Ave NE)','MN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','E. 28th St (Portland Ave S to Midtown Greenway)','MN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','E. 26th St (Hiawatha Ave and 5th Ave S)','MN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Park Ave S (3rd St S to 4th St S)','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Portland Ave S (3rd St S to 5th St S)','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Franklin Ave Bridge','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Franklin Avenue E (29th Ave S/Riverside Ave S and Seabury Ave)','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Broadway St NE (Stinson Blvd NE to Industrial Blvd NE)','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','3rd Ave S (1st St S to 16th St E)','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Blaisdell Ave S (29th St W to 40th St)','MN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','Washington Ave S (Hennepin Ave to 5th Ave S)','MN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','3rd Ave/Central Ave (1st St S to University Ave SE)','MN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','26th St W (Portland Ave S to Hennepin Ave S)','MN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','28th St W (Portland Ave S to Hennepin Ave S)','MN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Minneapolis','27th Ave NE (Marshall St SE to University Ave NE)','MN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('St Paul','Jackson Street (St. Paul’s Mississippi River to Capitol Building)','MN','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Kansas City','Grand Boulevard bridge over I-670','MO','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Springfield','Main Ave (College St and Mill St)','MO','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('St. Louis','Chestnut St (4th to 20th)','MO','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Missoula','Higgins Ave','MT','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Missoula','Maurice Ave (S 6th St E and S 5th St E)','MT','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Missoula','Maurice Ave (S 6th St E and Connell Ave)','MT','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Kinston','Atlantic Ave (Nelson Street and Pollock Street)','NC','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Fargo','NP Avenue (10th Street and University Dr)','ND','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Lincoln','N Street','NE','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portsmouth','Lafayette Road and Middle Street','NH','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Hoboken','Sinatra Dr(Hudson River Waterfront)','NJ','built','2001');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Hoboken','Observer Hwy','NJ','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Newark','Mt Prospect Ave','NJ','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Ocean City','Aldrich Ave(Ninth Str to behind supermarket)','NJ','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Albuquerque','Fifth Street (Marquette and Tijeras)','NM','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Henderson','N Stephanie St (Galleria Drive to Russell)','NV','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Sparks','Victorian Ave (Nichols Boulevard to 7th St)','NV','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Sparks','Nichols Bouelvard (E Victorian Ave to Howard Dr)','NV','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Buffalo','Ohio Street bridge','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Eastern Parkway (Washington to Ralph)','NY','built','1874');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Ocean Parkway','NY','built','1894');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Manhattan Waterfront Greenway (West side)','NY','built','1993');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Tillary Street','NY','built','2005');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','9th Ave (14-23)','NY','built','2007');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Kent Ave','NY','built','2008');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Broadway (36-42)','NY','built','2008');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Grand St','NY','built','2008');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Sands St','NY','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Park Circle','NY','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','8th Ave (Bank-23)','NY','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Broadway (28-34, 47-58)','NY','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Kent Ave','NY','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','E 17th St (Union Square)','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Williamsburg Street','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Broadway (23-UnionSq)','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','8th Ave (23-34)','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Flushing Ave','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Columbus Ave (77-96)','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','2nd Ave (Houston-34)','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave (Houston-34)','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Prospect Park West','NY','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Borinquen PL','NY','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave (34-57)','NY','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Bergen St (in front of the 78th Precinct)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Eastern Parkway (Grand Army Plaza to Washington)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','8th Ave (34-42)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','9th Ave (33-42)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave (60-72)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','8th Ave (42-Columbus Circle)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','9th Ave (42-59)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','2nd Ave (100-125)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Allen/Pike St','NY','built 2009-2012','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave (72-125)','NY','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','E 37 St (East River Greenway to E 38th St)','NY','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Atlantic Basin','NY','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Lafayette St/4th Ave (Great Jones St to E 12th St))','NY','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Kent Ave South (Clymer St to Williamsburg)','NY','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Hudson St (W Houston St to 8th Ave)','NY','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Paerdegat Ave N','NY','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','W 170th St (Hven Ave to Edgecombe Ave)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Greenpoint Ave Bridge ( Kingsland Ave to Review Ave)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','University Ave (Merriam Ave to High Bridge)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Fort George Hill (Ft George Ave to Dyckman St)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Vernon Boulevard (46th Ave to 30th Dr)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Clinton St (South St waterfront to Grand St)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Seaview Ave (E 108th St to Canarise Pier)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Edgecombe Ave (Hudson Greenway to Broadway/FT Washington-High Bridge)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Queens Blvd. Phase I (50th St to 73rd St)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave (E 49th St to E 55th St)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Honeywell St Bridge (Skillman Ave to Northern Blvd)','NY','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','E 17th St (Union Square E to E 12th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Food Center Drive (farragut St-Halleck St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave (E 55th to E 59th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Shore Blvd (Ditmars Blvd to Astoria Park S)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Van Siclen Ave (Seaview Ave to Jamaica Bay Greenway)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Bruckner blvd (Hunts Point Ave to Longwood Ave)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Ave and East 124th st (Willis Ave Bridge to 2nd Ave)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','2nd Ave (E 105th St to E 84th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Columbus Ave (W 69th St to W 59th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Avenue V, Hendrickson St (Ave U to Flatbush Ave)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Chrystie St (Canal St to Houston St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Jay St (Sands St and Fulton St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Pulaski Bridge (Eagle St to Jackson Ave)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','6th Ave (W 8th and W 33rd St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Amsterdam Ave (72nd St to W110th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Queens Boulevard Phase II (Eliot Ave and 74th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','20th Ave (Shore Blvd and 37th St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','South Street (Rutgers Sl to Montgomery St)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Hoyt Avenue N (27th St to 19th St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','2nd Ave (E 59th St to E 43rd St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Broadway - Flatiron Shared Streets (W 23rd St - W 26th St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Loring Avenue (Euclid Ave - Fountain Ave)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Shore Front Parkway (B 73rd St - B 108th St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','111th Street, 108th Street (Horace Harding Expy - 46th Ave)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','8th Avenue (W 42nd St to W 43rd St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Adam St (Johnson St - Red Cross Pl)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Tillary Street (Adams St - Jay St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Oceania Street, 210th Street (Horace Harding Expy - Vanderbilt Pkwy 1)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','1st Avenue (E 47th St - E 48th St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Centre Street, Park Row (Brooklyn Bridge - Spruce St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','5th Avenue (E 23rd St - Washington Sq N)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Del Valle Square, Bruckner Boulevard (Hunts Pt Ave - Bryant Ave)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Jay Street, York Street, Prospect Street (York St - Prospect St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','South 4th Street, Borinquen Place, South 5th Street (Berry St - Marcy St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','2nd Avenue (E 84th St - E 74th St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','7th Avenue (W 30th St - W 11th St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Cypress Hills Street (Cooper Ave - Jackie Robinson Pkwy)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Dyckman Street (Broadway - 10th Ave)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','E 133rd Street, St Ann''s Avenue, Willow Avenue (E 138th St - E 132nd St)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Gerritsen Avenue (Ave X - Southern Terminus)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Northern Boulevard, East Hampton Boulevard (Douglaston Pkwy - Horace Harding Expy)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Queens Boulevard Phase III (Eliot Ave - Yellowstone Blvd)','NY','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('New York City','Delancey Street','NY','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Rochester','N Chestnut St (E Main and Andrews)','NY','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Syracuse','University/Genesee','NY','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Akron','South Main St','OH','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Cincinnati','Central Parkway (Elm Street to Marshall Avenue)','OH','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Columbus','Summit St (Hudson St to 11th Ave)','OH','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Oklahoma City','Will Rogers Trail','OK','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Beaverton','SW 155th Ave','OR','built','1996');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Bend','Reed Market Rd (Century to Bond)','OR','built','2003');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Bend','NW Riverside Blvd between Broadway and Wall St','OR','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Eugene','Ayers Rd','OR','built','2002');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Eugene','Alder St.','OR','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Hillsboro','Ronler Dr (229th Ave and Cornelius Pass Rd)','OR','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Hillsboro','231st Ave (light rail tracks to Campus Court)','OR','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Hillsboro','Veteran''s Drive (28th Ave to Brookwood Parkway)','OR','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','N Bruce Ave (western entrance of Pier Park to Reno)','OR','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','Terminal Rd','OR','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SW Broadway','OR','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SW Moody','OR','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NE Cully Boulevard','OR','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NW Marshall St (10th Ave to 11th Ave)','OR','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NE Multnomah (NE 3rd to 15th)','OR','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SE Hawthorne Boulevard','OR','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SW 5th Ave (Jackson St to Lincoln St)','OR','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SW Multnomah (22nd to 31st)','OR','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SE Morrision (Grand Ave and MLK)','OR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NE 21st Ave (Multnomah and I-84)','OR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','2nd Ave (SW Stark and NW Everett)','OR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SW Porter Street (SW Moody to Tilikum Crossing)','OR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NE Cornfoot Street (NE Alderwood to NE Fleming)','OR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','SE Tilikum Way (SE 2nd Ave to SE Water St)','OR','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','Naito Parkway','OR','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NE 1st Avenue (Steel Bridge and the Lloyd District)','OR','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','NE Multnomah at 9th','OR','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Portland','North Greeley Avenue','OR','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Tigard','Durham Rd (85th to 92nd)','OR','built','1986');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Woodburn','Parr Rd (Stubb to Boones Ferry)','OR','built','unknown');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Munhall','E Waterfront Dr','PA','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','22nd (Ben Franklin Parkway to Spring Garden St.)','PA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','JFK Blvd (15th to 19th)','PA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','Market St (20th to 15th)','PA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','Chestnut Street (34th and 45th Streets)','PA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','Frankford Ave (Connect Pennypack Trail)','PA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','Ryan Ave (Rowland and Lexington ave)','PA','bulit','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','5th Street Tunnel under the Ben Franklin Bridge','PA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Philadelphia','Part of the Delaware Waterfront Greenway (Spring Garden St and Penn St.)','PA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','Saline Street (Greenfield Avenue and Swinburne St/Eliza Furnace Trail)','PA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','Schenley Drive (Schenley Plaza to Anderson Playground)','PA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','Penn Avenue (Sixth and 16th st)','PA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','Roberto Clemente Bridge (Roberto Clemente Statue to 10th St Bypass)','PA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','Schenley Drive Extension to Bigelow','PA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','E Ohio Street in the North Side (Chestnut to East St)','PA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pittsburgh','Forbes Ave (Bigelow Blvd to Craig St)','PA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Providence','Fountain Street','RI','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chattanooga','Broad St (MLK Boulevard to Aquarium Way)','TN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Chattanooga','Long St. (25th St. - 20th St.)','TN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Memphis','Overton Park Ave.','TN','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Memphis','Broad Ave (Phase1)','TN','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Memphis','Danny Thomas Blvd.','TN','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Memphis','Crump Ave.','TN','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Memphis','Kirby Rd.','TN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Memphis','Cleveland St.','TN','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Nashville','28th Ave','TN','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Lance Armstrong Bikeway (Cesar Chavez)','TX','built','2009');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','4th Street (I35 to Trinity)','TX','built','2010');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Rio Grande (MLK to 24th)','TX','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Bluebonnet (S. Lamar to Rabb Glen Street)','TX','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Pedernales (6th to Webberville Rd)','TX','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Guadalupe (MLK to 24th)','TX','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Barton Springs Road (S 1st Street to Lamar Boulevard)','TX','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Furness Dr (Park Plaza Dr and North Plaza)','TX','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Trinity (3rd to 4th)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Sendera Mesa (Slaughter to Ramie Run)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','San Jacinto (Dean Keeton to Speedway)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','3rd (Guadalupe to Trinity)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','51st (Springdale to 183)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Zach Scott (Berkman to Manor) Cycle track','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Pedernales/Webberville (Canterbury to 6th and Webberville to Pleasant Valley','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Tilley Street (Manor to 51st) Cycle track','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Arroyo Seco (Koenig to Woodrow)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Hancock bridge (Valley Oak Drive to W. Frances Place)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','3rd (Shoal Creek to Guadalupe)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Hancock (Valley Oak Drive to Bull Creek Rd)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Lakeshore (Riverside to Pleasant Valley)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Barton Hills (Robert E Lee to Barton Skwy)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','Rio Grande (24th to 29th) Bicycle Boulevard','TX','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Austin','3rd St (Seaholm District to Trinity Street)','TX','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Dallas','E Jefferson Blvd bridge(downtown to Oak Cliff)','TX','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Dallas','Houston St in Victory Park','TX','Built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Dallas','Cadiz (Lamar to Riverfront)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Dallas','Sylvan Avenue Bridge','TX','Built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Denton','Avenue C','TX','built 1980s','1985');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('El Paso','Stanton St (Baltimore Avenue to Rio Grande Ave)','TX','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Fort Worth','Shiver (Trace Ridge and Park Vista)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Fort Worth','Trace Ridge (Shiver and Heritage Trace)','TX','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Houston','Lamar St. (Sam Houston Park to Discovery Green park)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('San Antonio','E Market St (Bowie St to I-37)','TX','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Ogden','Grant Avenue (between 20th and 22nd st)','UT','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Salt Lake City','300 East (test)','UT','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Salt Lake City','300 South (Broadway)','UT','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Alexandria','North Van Dorn St (W Braddock Rd and Menokin Dr)','VA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Arlington','Wilson Boulevard (N. Quinn Street and N. Courthouse Road )','VA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Arlington','Wilson Boulevard (N. Oak and N. Quinn Streets)','VA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Arlington','Eads St (15th St Suth and 23rd St South)','VA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Charlottesville','6th St SE (Garrett St to Monticello Ave)','VA','built','2012');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Pentagon City (Arlington)','S. Hayes St (15th Street to S. Eads Street)','VA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('South Burlington','Swift Street','VT','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('King County','High Point Way','WA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Cherry St (6th ave to 7th Ave)','WA','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','NE 65th St (Burke-Gilman Trail to Sand Point Way NE)','WA','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Alki Avenue SW','WA','built','2013');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','NE 40th St (15th Ave and Brooklyn Ave)','WA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Dexter Ave N (Harrison St to John St)','WA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','2nd Ave (between Pike Place Market and Pioneer Square)','WA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Linden Ave N (N 128th and N 145th St)','WA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Broadway (Denny St to Yesler St)','WA','built','2014');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Brooklyn Ave NE (NE 40th St to NE Campus Pkwy)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Pike St (1st Ave to 2nd Ave','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','15th Ave NE (Cowen PL NE to NE 62nd St)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Sand Point Way NE (40th Ave NE to Penny Dr)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','NE Campus Parkway (Brooklyn Ave NE to Roosevelt Way NE)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Cowen Pl NE (University Way NE to NE 62nd St)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Mercer St (5th Ave to Dexter Ave)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','th Ave N (Mercer St to Republican St)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Pinehurst Way NE (NE 123rd St to NE 112th St)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','NE Ravenna Blvd (E Green Lake Way N to 15th Ave NE)','WA','built','2015');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','7th Ave (Blanchard St to Westlake Ave)','WA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','34th St (Fremont Ave N and Phinney Ave N)','WA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Yesler Way (I-5 to 10th Ave E)','WA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Westlake Ave N (Aloha St to Ship Canal Trail)','WA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Roosevelt Way NE (NE 65th St to Fuhrman Ave E)','WA','built','2016');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','9th Ave N (Westlake Ave to Mercer St)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','N 92nd St (Wallingford Ave N to Meridian Ave N)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','N 92nd St (Meridian Ave N to I-5 Bridge)','WA','built','2018');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Pike St (2nd Ave to 6th Ave)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Pine St (8th Ave to 5th Ave)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Pine St (4th Ave to 2nd Ave)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','NE Northlake Way (8th Ave NE to Eastlake Pl NE)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','NE Northlake Way (7th Ave NE to 8th Ave NE)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Western Ave (University St to Virginia St)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Seattle','Roy St (Dexter Ave N to 9th Ave N)','WA','built','2017');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Madison','University Ave.','WI','built','1983');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Milwaukee','Bay St (Laguna and Fillmore st)','WI','built','2011');
INSERT INTO outdoors.biking(City,Street,State,Status,Year_completed_or_to_be_built) VALUES ('Jackson','West Broadway (US 89/191) Flat Creek Bridge to WY22/Buffalo Way','WY','built','2015');
