CREATE TABLE IF NOT EXISTS outdoors.skiing(
   Resort_Name VARCHAR(45) NOT NULL
  ,Country     VARCHAR(3) NOT NULL
  ,State       VARCHAR(14) NOT NULL
  ,URL         VARCHAR(83) NOT NULL
  ,Altitude    INTEGER  NOT NULL
);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cloudmont-ski-resort','USA','Alabama','http://www.skiresort.info/ski-resort/cloudmont-ski-resort/',548);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alyeska-resort-girdwood','USA','Alaska','http://www.skiresort.info/ski-resort/alyeska-resort-girdwood/',840);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('eaglecrest-juneau','USA','Alaska','http://www.skiresort.info/ski-resort/eaglecrest-juneau/',820);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('moose-mountain','USA','Alaska','http://www.skiresort.info/ski-resort/moose-mountain/',595);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpenglow-at-arctic-valley','USA','Alaska','http://www.skiresort.info/ski-resort/alpenglow-at-arctic-valley/',1188);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('skiland-mt-aurora','USA','Alaska','http://www.skiresort.info/ski-resort/skiland-mt-aurora/',745);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hilltop-anchorage','USA','Alaska','http://www.skiresort.info/ski-resort/hilltop-anchorage/',140);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-eyak','USA','Alaska','http://www.skiresort.info/ski-resort/mt-eyak/',366);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hillberg-ski-area','USA','Alaska','http://www.skiresort.info/ski-resort/hillberg-ski-area/',120);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('black-rapid','USA','Alaska','http://www.skiresort.info/ski-resort/black-rapid/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('fort-wainwrightbirch-hill-fairbanks','USA','Alaska','http://www.skiresort.info/ski-resort/fort-wainwrightbirch-hill-fairbanks/',300);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('h2o-guides','USA','Alaska','http://www.skiresort.info/ski-resort/h2o-guides/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('jerrys-heliski-alaska','USA','Alaska','http://www.skiresort.info/ski-resort/jerrys-heliski-alaska/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('north-bicentennial-park','USA','Alaska','http://www.skiresort.info/ski-resort/north-bicentennial-park/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('points-north-heli-adventures','USA','Alaska','http://www.skiresort.info/ski-resort/points-north-heli-adventures/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ravenswood','USA','Alaska','http://www.skiresort.info/ski-resort/ravenswood/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('valdez-heli-ski-guides','USA','Alaska','http://www.skiresort.info/ski-resort/valdez-heli-ski-guides/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('arizona-snowbowl','USA','Arizona','http://www.skiresort.info/ski-resort/arizona-snowbowl/',3505);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sunrise-park','USA','Arizona','http://www.skiresort.info/ski-resort/sunrise-park/',3330);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('elk-ridge-williams','USA','Arizona','http://www.skiresort.info/ski-resort/elk-ridge-williams/',2452);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-lemmon-ski-valley','USA','Arizona','http://www.skiresort.info/ski-resort/mt-lemmon-ski-valley/',2750);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mammoth-mountain','USA','California','http://www.skiresort.info/ski-resort/mammoth-mountain/',3369);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('june-mountain','USA','California','http://www.skiresort.info/ski-resort/june-mountain/',3075);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bear-mountain-big-bear-lake','USA','California','http://www.skiresort.info/ski-resort/bear-mountain-big-bear-lake/',2684);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-summit-big-bear-lake','USA','California','http://www.skiresort.info/ski-resort/snow-summit-big-bear-lake/',2500);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bear-valley','USA','California','http://www.skiresort.info/ski-resort/bear-valley/',2590);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('china-peak','USA','California','http://www.skiresort.info/ski-resort/china-peak/',2654);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-valley','USA','California','http://www.skiresort.info/ski-resort/snow-valley/',2390);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mountain-high-east','USA','California','http://www.skiresort.info/ski-resort/mountain-high-east/',2496);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mountain-high-north','USA','California','http://www.skiresort.info/ski-resort/mountain-high-north/',2287);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mountain-high-west','USA','California','http://www.skiresort.info/ski-resort/mountain-high-west/',2410);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('dodge-ridge','USA','California','http://www.skiresort.info/ski-resort/dodge-ridge/',2499);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-baldy','USA','California','http://www.skiresort.info/ski-resort/mt-baldy/',2620);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-shasta-ski-park','USA','California','http://www.skiresort.info/ski-resort/mt-shasta-ski-park/',2100);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-waterman','USA','California','http://www.skiresort.info/ski-resort/mt-waterman/',2440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('badger-pass','USA','California','http://www.skiresort.info/ski-resort/badger-pass/',2440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alta-sierra-shirley-meadows','USA','California','http://www.skiresort.info/ski-resort/alta-sierra-shirley-meadows/',2160);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('buckhorn-ski-and-snowboard-club','USA','California','http://www.skiresort.info/ski-resort/buckhorn-ski-and-snowboard-club/',2253);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('carson-ski-resort','USA','California','http://www.skiresort.info/ski-resort/carson-ski-resort/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('coppervale','USA','California','http://www.skiresort.info/ski-resort/coppervale/',1825);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('plumas-eureka-ski-bowl','USA','California','http://www.skiresort.info/ski-resort/plumas-eureka-ski-bowl/',1874);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sierra-summit','USA','California','http://www.skiresort.info/ski-resort/sierra-summit/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('stover-mountain','USA','California','http://www.skiresort.info/ski-resort/stover-mountain/',1710);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('beaver-creek','USA','Colorado','http://www.skiresort.info/ski-resort/beaver-creek/',3488);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('aspen-highlands','USA','Colorado','http://www.skiresort.info/ski-resort/aspen-highlands/',3559);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('aspen-mountain','USA','Colorado','http://www.skiresort.info/ski-resort/aspen-mountain/',3418);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('buttermilk-mountain','USA','Colorado','http://www.skiresort.info/ski-resort/buttermilk-mountain/',3018);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowmass','USA','Colorado','http://www.skiresort.info/ski-resort/snowmass/',3813);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('vail','USA','Colorado','http://www.skiresort.info/ski-resort/vail/',3433);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('steamboat','USA','Colorado','http://www.skiresort.info/ski-resort/steamboat/',3221);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('breckenridge','USA','Colorado','http://www.skiresort.info/ski-resort/breckenridge/',3914);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('keystone','USA','Colorado','http://www.skiresort.info/ski-resort/keystone/',3651);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('winter-park-resort','USA','Colorado','http://www.skiresort.info/ski-resort/winter-park-resort/',3676);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('copper-mountain','USA','Colorado','http://www.skiresort.info/ski-resort/copper-mountain/',3767);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('telluride','USA','Colorado','http://www.skiresort.info/ski-resort/telluride/',3815);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('crested-butte','USA','Colorado','http://www.skiresort.info/ski-resort/crested-butte/',3707);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('arapahoe-basin','USA','Colorado','http://www.skiresort.info/ski-resort/arapahoe-basin/',3790);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('eldora-mountain','USA','Colorado','http://www.skiresort.info/ski-resort/eldora-mountain/',3292);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('purgatory-durango','USA','Colorado','http://www.skiresort.info/ski-resort/purgatory-durango/',3299);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('loveland','USA','Colorado','http://www.skiresort.info/ski-resort/loveland/',3871);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('granby-ranch','USA','Colorado','http://www.skiresort.info/ski-resort/granby-ranch/',2804);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('monarch','USA','Colorado','http://www.skiresort.info/ski-resort/monarch/',3630);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powderhorn','USA','Colorado','http://www.skiresort.info/ski-resort/powderhorn/',3000);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wolf-creek','USA','Colorado','http://www.skiresort.info/ski-resort/wolf-creek/',3628);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sunlight-mountain','USA','Colorado','http://www.skiresort.info/ski-resort/sunlight-mountain/',3015);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('silverton-mountain','USA','Colorado','http://www.skiresort.info/ski-resort/silverton-mountain/',3790);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cooper','USA','Colorado','http://www.skiresort.info/ski-resort/cooper/',3566);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('echo-mountain-park-idaho-springs','USA','Colorado','http://www.skiresort.info/ski-resort/echo-mountain-park-idaho-springs/',3401);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snoebahn-centennial','USA','Colorado','http://www.skiresort.info/ski-resort/snoebahn-centennial/',1710);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hesperus-ski-area','USA','Colorado','http://www.skiresort.info/ski-resort/hesperus-ski-area/',2706);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('howelsen-hill-steamboat-springs','USA','Colorado','http://www.skiresort.info/ski-resort/howelsen-hill-steamboat-springs/',2175);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('kendall-mountain-silverton','USA','Colorado','http://www.skiresort.info/ski-resort/kendall-mountain-silverton/',3000);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lake-city-ski-hill','USA','Colorado','http://www.skiresort.info/ski-resort/lake-city-ski-hill/',2771);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('stagecoach','USA','Colorado','http://www.skiresort.info/ski-resort/stagecoach/',2867);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mohawk-mountain','USA','Connecticut','http://www.skiresort.info/ski-resort/mohawk-mountain/',454);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sundown','USA','Connecticut','http://www.skiresort.info/ski-resort/sundown/',330);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-southington','USA','Connecticut','http://www.skiresort.info/ski-resort/mt-southington/',173);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powder-ridge-mountain-park-resort','USA','Connecticut','http://www.skiresort.info/ski-resort/powder-ridge-mountain-park-resort/',245);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('woodbury','USA','Connecticut','http://www.skiresort.info/ski-resort/woodbury/',259);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('winterclub-indoor-ski-snowboard-winter-park','USA','Florida','http://www.skiresort.info/ski-resort/winterclub-indoor-ski-snowboard-winter-park/',34);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cataldo-peak-adventures','USA','Idaho','http://www.skiresort.info/ski-resort/cataldo-peak-adventures/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bald-mountain-sun-valley','USA','Idaho','http://www.skiresort.info/ski-resort/bald-mountain-sun-valley/',2788);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('dollar-mountain-sun-valley','USA','Idaho','http://www.skiresort.info/ski-resort/dollar-mountain-sun-valley/',2023);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('schweitzer-mountain-resort','USA','Idaho','http://www.skiresort.info/ski-resort/schweitzer-mountain-resort/',1950);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('tamarack-resort','USA','Idaho','http://www.skiresort.info/ski-resort/tamarack-resort/',2347);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('brundage-mountain','USA','Idaho','http://www.skiresort.info/ski-resort/brundage-mountain/',2328);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('silver-mountain','USA','Idaho','http://www.skiresort.info/ski-resort/silver-mountain/',1920);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bogus-basin','USA','Idaho','http://www.skiresort.info/ski-resort/bogus-basin/',2311);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lookout-pass','USA','Idaho','http://www.skiresort.info/ski-resort/lookout-pass/',1675);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pebble-creek','USA','Idaho','http://www.skiresort.info/ski-resort/pebble-creek/',2609);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('kelly-canyon','USA','Idaho','http://www.skiresort.info/ski-resort/kelly-canyon/',2030);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pomerelle','USA','Idaho','http://www.skiresort.info/ski-resort/pomerelle/',2640);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('soldier-mountain','USA','Idaho','http://www.skiresort.info/ski-resort/soldier-mountain/',2188);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('magic-mountain-resort','USA','Idaho','http://www.skiresort.info/ski-resort/magic-mountain-resort/',2207);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowhaven','USA','Idaho','http://www.skiresort.info/ski-resort/snowhaven/',1730);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bald-mountain','USA','Idaho','http://www.skiresort.info/ski-resort/bald-mountain/',1463);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cottonwood-butte','USA','Idaho','http://www.skiresort.info/ski-resort/cottonwood-butte/',1707);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('eagle-island-park','USA','Idaho','http://www.skiresort.info/ski-resort/eagle-island-park/',781);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('rotarun','USA','Idaho','http://www.skiresort.info/ski-resort/rotarun/',1790);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('little-ski-hill','USA','Idaho','http://www.skiresort.info/ski-resort/little-ski-hill/',1700);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('chestnut-mountain','USA','Illinois','http://www.skiresort.info/ski-resort/chestnut-mountain/',335);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('raging-buffalo-algonquin','USA','Illinois','http://www.skiresort.info/ski-resort/raging-buffalo-algonquin/',260);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('villa-olivia-bartlett','USA','Illinois','http://www.skiresort.info/ski-resort/villa-olivia-bartlett/',258);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowstar','USA','Illinois','http://www.skiresort.info/ski-resort/snowstar/',235);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('four-lakes','USA','Illinois','http://www.skiresort.info/ski-resort/four-lakes/',220);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('plumtree-ski-hill-fawnridge','USA','Illinois','http://www.skiresort.info/ski-resort/plumtree-ski-hill-fawnridge/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('paoli-peaks','USA','Indiana','http://www.skiresort.info/ski-resort/paoli-peaks/',251);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('perfect-north-slopes','USA','Indiana','http://www.skiresort.info/ski-resort/perfect-north-slopes/',244);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sundown-mountain-resort','USA','Iowa','http://www.skiresort.info/ski-resort/sundown-mountain-resort/',350);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('crescent-hills','USA','Iowa','http://www.skiresort.info/ski-resort/crescent-hills/',457);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('seven-oaks','USA','Iowa','http://www.skiresort.info/ski-resort/seven-oaks/',330);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('nor-ski-runs-decorah','USA','Iowa','http://www.skiresort.info/ski-resort/nor-ski-runs-decorah/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('riverside-hills','USA','Iowa','http://www.skiresort.info/ski-resort/riverside-hills/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sleepy-hollow-sports-park-des-moines','USA','Iowa','http://www.skiresort.info/ski-resort/sleepy-hollow-sports-park-des-moines/',286);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sunset-ski-area','USA','Iowa','http://www.skiresort.info/ski-resort/sunset-ski-area/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sunday-river','USA','Maine','http://www.skiresort.info/ski-resort/sunday-river/',957);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sugarloaf','USA','Maine','http://www.skiresort.info/ski-resort/sugarloaf/',1286);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('saddleback','USA','Maine','http://www.skiresort.info/ski-resort/saddleback/',1220);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('shawnee-peak','USA','Maine','http://www.skiresort.info/ski-resort/shawnee-peak/',550);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-abram','USA','Maine','http://www.skiresort.info/ski-resort/mt-abram/',610);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lost-valley','USA','Maine','http://www.skiresort.info/ski-resort/lost-valley/',166);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('camden-snow-bowl','USA','Maine','http://www.skiresort.info/ski-resort/camden-snow-bowl/',320);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bigrock-mountain','USA','Maine','http://www.skiresort.info/ski-resort/bigrock-mountain/',498);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-squaw','USA','Maine','http://www.skiresort.info/ski-resort/big-squaw/',933);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('black-mountain-rumford','USA','Maine','http://www.skiresort.info/ski-resort/black-mountain-rumford/',650);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hermon-mountain','USA','Maine','http://www.skiresort.info/ski-resort/hermon-mountain/',140);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('spruce-mountain-jay','USA','Maine','http://www.skiresort.info/ski-resort/spruce-mountain-jay/',183);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('titcomb-mountain','USA','Maine','http://www.skiresort.info/ski-resort/titcomb-mountain/',210);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lonesome-pine-trails-fort-kent','USA','Maine','http://www.skiresort.info/ski-resort/lonesome-pine-trails-fort-kent/',299);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-jefferson','USA','Maine','http://www.skiresort.info/ski-resort/mt-jefferson/',230);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('eaton-mountain','USA','Maine','http://www.skiresort.info/ski-resort/eaton-mountain/',140);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('quoggy-jo-ski-center-presque-isle','USA','Maine','http://www.skiresort.info/ski-resort/quoggy-jo-ski-center-presque-isle/',275);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powderhouse-hill-south-berwick','USA','Maine','http://www.skiresort.info/ski-resort/powderhouse-hill-south-berwick/',80);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pinnacle-park-pittsfield','USA','Maine','http://www.skiresort.info/ski-resort/pinnacle-park-pittsfield/',96);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('seacoast-snow-park','USA','Maine','http://www.skiresort.info/ski-resort/seacoast-snow-park/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wisp-mchenry-deep-creek-lake','USA','Maryland','http://www.skiresort.info/ski-resort/wisp-mchenry-deep-creek-lake/',950);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('jiminy-peak','USA','Massachusetts','http://www.skiresort.info/ski-resort/jiminy-peak/',725);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wachusett-mountain','USA','Massachusetts','http://www.skiresort.info/ski-resort/wachusett-mountain/',611);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('catamount','USA','Massachusetts','http://www.skiresort.info/ski-resort/catamount/',580);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('butternut-basin','USA','Massachusetts','http://www.skiresort.info/ski-resort/butternut-basin/',540);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('berkshire-east','USA','Massachusetts','http://www.skiresort.info/ski-resort/berkshire-east/',561);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('nashoba-valley','USA','Massachusetts','http://www.skiresort.info/ski-resort/nashoba-valley/',128);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bradford','USA','Massachusetts','http://www.skiresort.info/ski-resort/bradford/',80);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ward-hill-shrewsbury','USA','Massachusetts','http://www.skiresort.info/ski-resort/ward-hill-shrewsbury/',160);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bousquet','USA','Massachusetts','http://www.skiresort.info/ski-resort/bousquet/',566);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blue-hills','USA','Massachusetts','http://www.skiresort.info/ski-resort/blue-hills/',180);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blandford','USA','Massachusetts','http://www.skiresort.info/ski-resort/blandford/',440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('otis-ridge','USA','Massachusetts','http://www.skiresort.info/ski-resort/otis-ridge/',480);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mount-greylock-south-williamstown','USA','Massachusetts','http://www.skiresort.info/ski-resort/mount-greylock-south-williamstown/',481);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('boyne-highlands','USA','Michigan','http://www.skiresort.info/ski-resort/boyne-highlands/',408);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('boyne-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/boyne-mountain/',372);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('nubs-nob-ski-area','USA','Michigan','http://www.skiresort.info/ski-resort/nubs-nob-ski-area/',403);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('crystal-mountain-mi','USA','Michigan','http://www.skiresort.info/ski-resort/crystal-mountain-mi/',359);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('shanty-creek-resorts-schuss-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/shanty-creek-resorts-schuss-mountain/',356);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('shanty-creek-resorts-summit-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/shanty-creek-resorts-summit-mountain/',300);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-powderhorn-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/big-powderhorn-mountain/',540);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blackjack','USA','Michigan','http://www.skiresort.info/ski-resort/blackjack/',510);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('indianhead-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/indianhead-mountain/',554);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('otsego-gaylord','USA','Michigan','http://www.skiresort.info/ski-resort/otsego-gaylord/',422);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-brighton','USA','Michigan','http://www.skiresort.info/ski-resort/mt-brighton/',340);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-bohemia','USA','Michigan','http://www.skiresort.info/ski-resort/mt-bohemia/',445);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('treetops-sylvan','USA','Michigan','http://www.skiresort.info/ski-resort/treetops-sylvan/',405);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pine-knob','USA','Michigan','http://www.skiresort.info/ski-resort/pine-knob/',392);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-homestead-resort','USA','Michigan','http://www.skiresort.info/ski-resort/the-homestead-resort/',280);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ski-brule','USA','Michigan','http://www.skiresort.info/ski-resort/ski-brule/',565);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('caberfae-peaks','USA','Michigan','http://www.skiresort.info/ski-resort/caberfae-peaks/',465);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('marquette-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/marquette-mountain/',390);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpine-valley-white-lake','USA','Michigan','http://www.skiresort.info/ski-resort/alpine-valley-white-lake/',368);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mont-ripley','USA','Michigan','http://www.skiresort.info/ski-resort/mont-ripley/',330);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('norway-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/norway-mountain/',406);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pine-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/pine-mountain/',461);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bittersweet','USA','Michigan','http://www.skiresort.info/ski-resort/bittersweet/',324);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-holly','USA','Michigan','http://www.skiresort.info/ski-resort/mt-holly/',380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('swiss-valley','USA','Michigan','http://www.skiresort.info/ski-resort/swiss-valley/',360);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('timber-ridge','USA','Michigan','http://www.skiresort.info/ski-resort/timber-ridge/',287);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('porcupine-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/porcupine-mountain/',415);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cannonsburg-ski-area','USA','Michigan','http://www.skiresort.info/ski-resort/cannonsburg-ski-area/',280);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('apple-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/apple-mountain/',244);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-holiday','USA','Michigan','http://www.skiresort.info/ski-resort/mt-holiday/',274);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-snake','USA','Michigan','http://www.skiresort.info/ski-resort/snow-snake/',365);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hanson-hills','USA','Michigan','http://www.skiresort.info/ski-resort/hanson-hills/',390);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pando-park','USA','Michigan','http://www.skiresort.info/ski-resort/pando-park/',300);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mulligans-hollow-ski-bowl','USA','Michigan','http://www.skiresort.info/ski-resort/mulligans-hollow-ski-bowl/',233);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('gladstone-sports-park','USA','Michigan','http://www.skiresort.info/ski-resort/gladstone-sports-park/',220);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('al-quaal','USA','Michigan','http://www.skiresort.info/ski-resort/al-quaal/',451);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('challenge-mountain-walloon-lake','USA','Michigan','http://www.skiresort.info/ski-resort/challenge-mountain-walloon-lake/',325);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('missaukee-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/missaukee-mountain/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mott-mountain','USA','Michigan','http://www.skiresort.info/ski-resort/mott-mountain/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-mc-sauba','USA','Michigan','http://www.skiresort.info/ski-resort/mt-mc-sauba/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-zion-hill','USA','Michigan','http://www.skiresort.info/ski-resort/mt-zion-hill/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('petoskey-winter-sports-park','USA','Michigan','http://www.skiresort.info/ski-resort/petoskey-winter-sports-park/',241);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('riverview-highlands','USA','Michigan','http://www.skiresort.info/ski-resort/riverview-highlands/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('silver-ridge','USA','Michigan','http://www.skiresort.info/ski-resort/silver-ridge/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lutsen-mountains','USA','Minnesota','http://www.skiresort.info/ski-resort/lutsen-mountains/',503);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('afton-alps','USA','Minnesota','http://www.skiresort.info/ski-resort/afton-alps/',387);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('welch-village','USA','Minnesota','http://www.skiresort.info/ski-resort/welch-village/',323);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('giants-ridge','USA','Minnesota','http://www.skiresort.info/ski-resort/giants-ridge/',560);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wild-mountain','USA','Minnesota','http://www.skiresort.info/ski-resort/wild-mountain/',320);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('spirit-mountain','USA','Minnesota','http://www.skiresort.info/ski-resort/spirit-mountain/',390);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powder-ridge','USA','Minnesota','http://www.skiresort.info/ski-resort/powder-ridge/',432);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('buck-hill-ski-area','USA','Minnesota','http://www.skiresort.info/ski-resort/buck-hill-ski-area/',371);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('andes-tower-hills','USA','Minnesota','http://www.skiresort.info/ski-resort/andes-tower-hills/',494);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-kato','USA','Minnesota','http://www.skiresort.info/ski-resort/mt-kato/',313);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('buena-vista','USA','Minnesota','http://www.skiresort.info/ski-resort/buena-vista/',470);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('detroit-mountain','USA','Minnesota','http://www.skiresort.info/ski-resort/detroit-mountain/',490);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hyland-ski-snowboard-area','USA','Minnesota','http://www.skiresort.info/ski-resort/hyland-ski-snowboard-area/',310);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('coffee-mill-ski-area','USA','Minnesota','http://www.skiresort.info/ski-resort/coffee-mill-ski-area/',360);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mount-ski-gull','USA','Minnesota','http://www.skiresort.info/ski-resort/mount-ski-gull/',443);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('chester-bowl-park','USA','Minnesota','http://www.skiresort.info/ski-resort/chester-bowl-park/',380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('quadna-mountain','USA','Minnesota','http://www.skiresort.info/ski-resort/quadna-mountain/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hidden-valley-mo','USA','Missouri','http://www.skiresort.info/ski-resort/hidden-valley-mo/',240);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-creek','USA','Missouri','http://www.skiresort.info/ski-resort/snow-creek/',335);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-sky-resort','USA','Montana','http://www.skiresort.info/ski-resort/big-sky-resort/',3398);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('whitefish-mountain-resort','USA','Montana','http://www.skiresort.info/ski-resort/whitefish-mountain-resort/',2078);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bridger-bowl-bozeman','USA','Montana','http://www.skiresort.info/ski-resort/bridger-bowl-bozeman/',2682);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('red-lodge-mountain','USA','Montana','http://www.skiresort.info/ski-resort/red-lodge-mountain/',2870);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('montana-snowbowl','USA','Montana','http://www.skiresort.info/ski-resort/montana-snowbowl/',2316);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('discovery-ski-area','USA','Montana','http://www.skiresort.info/ski-resort/discovery-ski-area/',2484);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('showdown','USA','Montana','http://www.skiresort.info/ski-resort/showdown/',2500);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('teton-pass','USA','Montana','http://www.skiresort.info/ski-resort/teton-pass/',2194);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lost-trail-powder-mountain','USA','Montana','http://www.skiresort.info/ski-resort/lost-trail-powder-mountain/',2550);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blacktail-mountain','USA','Montana','http://www.skiresort.info/ski-resort/blacktail-mountain/',2066);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('great-divide','USA','Montana','http://www.skiresort.info/ski-resort/great-divide/',2210);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('turner-mountain','USA','Montana','http://www.skiresort.info/ski-resort/turner-mountain/',1814);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('maverick-mountain','USA','Montana','http://www.skiresort.info/ski-resort/maverick-mountain/',2596);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bear-paw-ski-bowl','USA','Montana','http://www.skiresort.info/ski-resort/bear-paw-ski-bowl/',1609);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('beef-trail','USA','Montana','http://www.skiresort.info/ski-resort/beef-trail/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('fairmont-hot-springs-fairmont','USA','Montana','http://www.skiresort.info/ski-resort/fairmont-hot-springs-fairmont/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('yellowstone-club','USA','Montana','http://www.skiresort.info/ski-resort/yellowstone-club/',3005);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('las-vegas-ski-and-snowboard-resort-lee-canyon','USA','Nevada','http://www.skiresort.info/ski-resort/las-vegas-ski-and-snowboard-resort-lee-canyon/',2856);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('elko-snobowl','USA','Nevada','http://www.skiresort.info/ski-resort/elko-snobowl/',2130);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('las-vegas-wet-planned','USA','Nevada','http://www.skiresort.info/ski-resort/las-vegas-wet-planned/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ruby-mountain','USA','Nevada','http://www.skiresort.info/ski-resort/ruby-mountain/',3350);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sky-tavern','USA','Nevada','http://www.skiresort.info/ski-resort/sky-tavern/',2517);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('loon-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/loon-mountain/',930);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bretton-woods','USA','New Hampshire','http://www.skiresort.info/ski-resort/bretton-woods/',945);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('gunstock','USA','New Hampshire','http://www.skiresort.info/ski-resort/gunstock/',690);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('attitash-mountain-resort','USA','New Hampshire','http://www.skiresort.info/ski-resort/attitash-mountain-resort/',716);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wildcat-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/wildcat-mountain/',1238);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-sunapee','USA','New Hampshire','http://www.skiresort.info/ski-resort/mt-sunapee/',828);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('waterville-valley','USA','New Hampshire','http://www.skiresort.info/ski-resort/waterville-valley/',1220);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ragged-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/ragged-mountain/',680);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cannon-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/cannon-mountain/',1243);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cranmore-mountain-resort','USA','New Hampshire','http://www.skiresort.info/ski-resort/cranmore-mountain-resort/',609);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pats-peak','USA','New Hampshire','http://www.skiresort.info/ski-resort/pats-peak/',426);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('crotched-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/crotched-mountain/',630);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('black-mountain-jackson','USA','New Hampshire','http://www.skiresort.info/ski-resort/black-mountain-jackson/',570);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('king-pine-purity-spring-resort','USA','New Hampshire','http://www.skiresort.info/ski-resort/king-pine-purity-spring-resort/',240);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('granite-gorge','USA','New Hampshire','http://www.skiresort.info/ski-resort/granite-gorge/',404);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('dartmouth-skiway','USA','New Hampshire','http://www.skiresort.info/ski-resort/dartmouth-skiway/',592);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('whaleback','USA','New Hampshire','http://www.skiresort.info/ski-resort/whaleback/',543);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mcintyre','USA','New Hampshire','http://www.skiresort.info/ski-resort/mcintyre/',155);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('campton-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/campton-mountain/',435);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('storrs-hill-lebanon','USA','New Hampshire','http://www.skiresort.info/ski-resort/storrs-hill-lebanon/',282);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mount-prospect-lancaster','USA','New Hampshire','http://www.skiresort.info/ski-resort/mount-prospect-lancaster/',520);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('abenaki','USA','New Hampshire','http://www.skiresort.info/ski-resort/abenaki/',250);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lynx-creek','USA','New Hampshire','http://www.skiresort.info/ski-resort/lynx-creek/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-eustis-littleton','USA','New Hampshire','http://www.skiresort.info/ski-resort/mt-eustis-littleton/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('red-hill-moultonborough','USA','New Hampshire','http://www.skiresort.info/ski-resort/red-hill-moultonborough/',260);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-hill-at-eastman','USA','New Hampshire','http://www.skiresort.info/ski-resort/snow-hill-at-eastman/',420);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('tenney-mountain','USA','New Hampshire','http://www.skiresort.info/ski-resort/tenney-mountain/',655);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-balsams','USA','New Hampshire','http://www.skiresort.info/ski-resort/the-balsams/',838);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('veterans-memorial-franklin','USA','New Hampshire','http://www.skiresort.info/ski-resort/veterans-memorial-franklin/',305);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mountain-creek-vernon','USA','New Jersey','http://www.skiresort.info/ski-resort/mountain-creek-vernon/',451);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('campgaw','USA','New Jersey','http://www.skiresort.info/ski-resort/campgaw/',290);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('american-dream-meadowlands-east-rutherford','USA','New Jersey','http://www.skiresort.info/ski-resort/american-dream-meadowlands-east-rutherford/',136);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('taos','USA','New Mexico','http://www.skiresort.info/ski-resort/taos/',3795);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('santa-fe','USA','New Mexico','http://www.skiresort.info/ski-resort/santa-fe/',3679);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('angel-fire','USA','New Mexico','http://www.skiresort.info/ski-resort/angel-fire/',3256);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('red-river','USA','New Mexico','http://www.skiresort.info/ski-resort/red-river/',3135);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('apache','USA','New Mexico','http://www.skiresort.info/ski-resort/apache/',3475);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sandia-peak','USA','New Mexico','http://www.skiresort.info/ski-resort/sandia-peak/',3140);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pajarito-mountain','USA','New Mexico','http://www.skiresort.info/ski-resort/pajarito-mountain/',3190);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cloudcroft','USA','New Mexico','http://www.skiresort.info/ski-resort/cloudcroft/',2773);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sipapu','USA','New Mexico','http://www.skiresort.info/ski-resort/sipapu/',2825);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('whiteface-lake-placid','USA','New York','http://www.skiresort.info/ski-resort/whiteface-lake-placid/',1340);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('windham-mountain','USA','New York','http://www.skiresort.info/ski-resort/windham-mountain/',945);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('gore-mountain','USA','New York','http://www.skiresort.info/ski-resort/gore-mountain/',1097);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hunter-mountain','USA','New York','http://www.skiresort.info/ski-resort/hunter-mountain/',975);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('holiday-valley','USA','New York','http://www.skiresort.info/ski-resort/holiday-valley/',685);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bristol-mountain','USA','New York','http://www.skiresort.info/ski-resort/bristol-mountain/',670);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('holimont','USA','New York','http://www.skiresort.info/ski-resort/holimont/',689);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('belleayre-mountain','USA','New York','http://www.skiresort.info/ski-resort/belleayre-mountain/',1045);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('greek-peak','USA','New York','http://www.skiresort.info/ski-resort/greek-peak/',640);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('plattekill','USA','New York','http://www.skiresort.info/ski-resort/plattekill/',1014);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('kissing-bridge','USA','New York','http://www.skiresort.info/ski-resort/kissing-bridge/',520);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('peekn-peak','USA','New York','http://www.skiresort.info/ski-resort/peekn-peak/',535);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('west-mountain','USA','New York','http://www.skiresort.info/ski-resort/west-mountain/',435);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('song-mountain','USA','New York','http://www.skiresort.info/ski-resort/song-mountain/',585);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('buffalo-ski-club','USA','New York','http://www.skiresort.info/ski-resort/buffalo-ski-club/',512);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hunt-hollow-ski-club','USA','New York','http://www.skiresort.info/ski-resort/hunt-hollow-ski-club/',360);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('swain','USA','New York','http://www.skiresort.info/ski-resort/swain/',600);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('labrador-mountain','USA','New York','http://www.skiresort.info/ski-resort/labrador-mountain/',570);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('thunder-ridge','USA','New York','http://www.skiresort.info/ski-resort/thunder-ridge/',267);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('toggenburg-ski-center','USA','New York','http://www.skiresort.info/ski-resort/toggenburg-ski-center/',543);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-peter','USA','New York','http://www.skiresort.info/ski-resort/mt-peter/',330);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hickory-ski-center','USA','New York','http://www.skiresort.info/ski-resort/hickory-ski-center/',583);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('titus-mountain','USA','New York','http://www.skiresort.info/ski-resort/titus-mountain/',423);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('willard-mountain-greenwich','USA','New York','http://www.skiresort.info/ski-resort/willard-mountain-greenwich/',429);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('woods-valley','USA','New York','http://www.skiresort.info/ski-resort/woods-valley/',325);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('holiday-mountain-ny','USA','New York','http://www.skiresort.info/ski-resort/holiday-mountain-ny/',440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('dry-hill','USA','New York','http://www.skiresort.info/ski-resort/dry-hill/',293);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('royal-mountain','USA','New York','http://www.skiresort.info/ski-resort/royal-mountain/',533);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sawkill-ski','USA','New York','http://www.skiresort.info/ski-resort/sawkill-ski/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-ridge','USA','New York','http://www.skiresort.info/ski-resort/snow-ridge/',540);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cockaigne-ski-area','USA','New York','http://www.skiresort.info/ski-resort/cockaigne-ski-area/',619);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('oak-mountain','USA','New York','http://www.skiresort.info/ski-resort/oak-mountain/',740);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('brantling-ski-slopes','USA','New York','http://www.skiresort.info/ski-resort/brantling-ski-slopes/',210);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mccauly-mountain','USA','New York','http://www.skiresort.info/ski-resort/mccauly-mountain/',700);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('four-seasons','USA','New York','http://www.skiresort.info/ski-resort/four-seasons/',185);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('beartown','USA','New York','http://www.skiresort.info/ski-resort/beartown/',304);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-pisgah','USA','New York','http://www.skiresort.info/ski-resort/mt-pisgah/',627);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-tupper-tupper-lake','USA','New York','http://www.skiresort.info/ski-resort/big-tupper-tupper-lake/',1082);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cazenovia','USA','New York','http://www.skiresort.info/ski-resort/cazenovia/',440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('dynamite-hill-chestertown','USA','New York','http://www.skiresort.info/ski-resort/dynamite-hill-chestertown/',281);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('huntington','USA','New York','http://www.skiresort.info/ski-resort/huntington/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('indian-lake','USA','New York','http://www.skiresort.info/ski-resort/indian-lake/',599);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('maple-ski-ridge','USA','New York','http://www.skiresort.info/ski-resort/maple-ski-ridge/',250);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('polar-peak','USA','New York','http://www.skiresort.info/ski-resort/polar-peak/',196);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('rocking-horse-ranch','USA','New York','http://www.skiresort.info/ski-resort/rocking-horse-ranch/',214);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('scotch-valley-resort','USA','New York','http://www.skiresort.info/ski-resort/scotch-valley-resort/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('shu-maker-mountain-little-falls','USA','New York','http://www.skiresort.info/ski-resort/shu-maker-mountain-little-falls/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sterling-forest-ski-center','USA','New York','http://www.skiresort.info/ski-resort/sterling-forest-ski-center/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-ridge-le-roy','USA','New York','http://www.skiresort.info/ski-resort/the-ridge-le-roy/',245);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('tuxedo-ridge','USA','New York','http://www.skiresort.info/ski-resort/tuxedo-ridge/',365);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('val-bialas-ski-center-utica','USA','New York','http://www.skiresort.info/ski-resort/val-bialas-ski-center-utica/',251);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('villa-roma','USA','New York','http://www.skiresort.info/ski-resort/villa-roma/',388);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sugar-mountain','USA','North Carolina','http://www.skiresort.info/ski-resort/sugar-mountain/',1589);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('beech-mountain','USA','North Carolina','http://www.skiresort.info/ski-resort/beech-mountain/',1678);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cataloochee','USA','North Carolina','http://www.skiresort.info/ski-resort/cataloochee/',1583);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('appalachian-ski-mountain','USA','North Carolina','http://www.skiresort.info/ski-resort/appalachian-ski-mountain/',1219);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wolf-ridge','USA','North Carolina','http://www.skiresort.info/ski-resort/wolf-ridge/',1432);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sapphire-valley','USA','North Carolina','http://www.skiresort.info/ski-resort/sapphire-valley/',1005);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('frost-fire-mountain','USA','North Dakota','http://www.skiresort.info/ski-resort/frost-fire-mountain/',440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bottineau-winter-park','USA','North Dakota','http://www.skiresort.info/ski-resort/bottineau-winter-park/',740);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('huff-hills','USA','North Dakota','http://www.skiresort.info/ski-resort/huff-hills/',680);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bears-den-mountain-fort-ransom','USA','North Dakota','http://www.skiresort.info/ski-resort/bears-den-mountain-fort-ransom/',430);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-trails','USA','Ohio','http://www.skiresort.info/ski-resort/snow-trails/',440);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mad-river-mountain','USA','Ohio','http://www.skiresort.info/ski-resort/mad-river-mountain/',445);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpine-valley-cleveland','USA','Ohio','http://www.skiresort.info/ski-resort/alpine-valley-cleveland/',457);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('boston-mills','USA','Ohio','http://www.skiresort.info/ski-resort/boston-mills/',270);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('brandywine','USA','Ohio','http://www.skiresort.info/ski-resort/brandywine/',270);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-creek-ski-area','USA','Ohio','http://www.skiresort.info/ski-resort/big-creek-ski-area/',320);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('clear-fork','USA','Ohio','http://www.skiresort.info/ski-resort/clear-fork/',420);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-bailey','USA','Oregon','http://www.skiresort.info/ski-resort/mt-bailey/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-bachelor','USA','Oregon','http://www.skiresort.info/ski-resort/mt-bachelor/',2763);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-hood-meadows','USA','Oregon','http://www.skiresort.info/ski-resort/mt-hood-meadows/',2225);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('timberline','USA','Oregon','http://www.skiresort.info/ski-resort/timberline/',2603);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hoodoo-ski-area','USA','Oregon','http://www.skiresort.info/ski-resort/hoodoo-ski-area/',1740);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-hood-skibowl','USA','Oregon','http://www.skiresort.info/ski-resort/mt-hood-skibowl/',1510);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('willamette-pass-crescent','USA','Oregon','http://www.skiresort.info/ski-resort/willamette-pass-crescent/',2036);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-ashland','USA','Oregon','http://www.skiresort.info/ski-resort/mt-ashland/',2286);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('anthony-lakes-mountain-resort','USA','Oregon','http://www.skiresort.info/ski-resort/anthony-lakes-mountain-resort/',2438);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('spout-springs','USA','Oregon','http://www.skiresort.info/ski-resort/spout-springs/',1670);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cooper-spur','USA','Oregon','http://www.skiresort.info/ski-resort/cooper-spur/',1325);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('warner-canyon-lakeview','USA','Oregon','http://www.skiresort.info/ski-resort/warner-canyon-lakeview/',1975);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('summit-ski-area-at-mt-hood','USA','Oregon','http://www.skiresort.info/ski-resort/summit-ski-area-at-mt-hood/',1312);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sand-master-park-florence','USA','Oregon','http://www.skiresort.info/ski-resort/sand-master-park-florence/',40);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ferguson-ridge','USA','Oregon','http://www.skiresort.info/ski-resort/ferguson-ridge/',1780);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('seven-springs','USA','Pennsylvania','http://www.skiresort.info/ski-resort/seven-springs/',915);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blue-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/blue-mountain/',470);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('liberty-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/liberty-mountain/',355);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('whitetail','USA','Pennsylvania','http://www.skiresort.info/ski-resort/whitetail/',549);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hidden-valley-pa','USA','Pennsylvania','http://www.skiresort.info/ski-resort/hidden-valley-pa/',890);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('roundtop','USA','Pennsylvania','http://www.skiresort.info/ski-resort/roundtop/',410);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bear-creek-mountain-resort','USA','Pennsylvania','http://www.skiresort.info/ski-resort/bear-creek-mountain-resort/',335);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('camelback','USA','Pennsylvania','http://www.skiresort.info/ski-resort/camelback/',623);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('elk-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/elk-mountain/',820);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blue-knob','USA','Pennsylvania','http://www.skiresort.info/ski-resort/blue-knob/',960);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('montage-mountain-resort','USA','Pennsylvania','http://www.skiresort.info/ski-resort/montage-mountain-resort/',594);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('shawnee-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/shawnee-mountain/',350);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-bear-at-masthope-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/big-bear-at-masthope-mountain/',450);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('big-boulder','USA','Pennsylvania','http://www.skiresort.info/ski-resort/big-boulder/',663);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('jack-frost-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/jack-frost-mountain/',610);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpine-mountain-ski-snow-tubing-center','USA','Pennsylvania','http://www.skiresort.info/ski-resort/alpine-mountain-ski-snow-tubing-center/',351);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('laurel-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/laurel-mountain/',837);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('spring-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/spring-mountain/',150);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('tussey-mountain','USA','Pennsylvania','http://www.skiresort.info/ski-resort/tussey-mountain/',553);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mystic-mountain-farmington','USA','Pennsylvania','http://www.skiresort.info/ski-resort/mystic-mountain-farmington/',619);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('eagle-rock','USA','Pennsylvania','http://www.skiresort.info/ski-resort/eagle-rock/',550);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mount-pleasant','USA','Pennsylvania','http://www.skiresort.info/ski-resort/mount-pleasant/',450);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sawmill-mountain-resort','USA','Pennsylvania','http://www.skiresort.info/ski-resort/sawmill-mountain-resort/',620);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('boyce-park','USA','Pennsylvania','http://www.skiresort.info/ski-resort/boyce-park/',380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('denton-hill-state-park','USA','Pennsylvania','http://www.skiresort.info/ski-resort/denton-hill-state-park/',750);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('yawgoo-valley','USA','Rhode Island','http://www.skiresort.info/ski-resort/yawgoo-valley/',96);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('terry-peak','USA','South Dakota','http://www.skiresort.info/ski-resort/terry-peak/',2130);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('deer-mountain','USA','South Dakota','http://www.skiresort.info/ski-resort/deer-mountain/',2028);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('great-bear-ski-area','USA','South Dakota','http://www.skiresort.info/ski-resort/great-bear-ski-area/',470);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ober-gatlinburg','USA','Tennessee','http://www.skiresort.info/ski-resort/ober-gatlinburg/',1006);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bearfire-resort-dallas-fort-worth-planned','USA','Texas','http://www.skiresort.info/ski-resort/bearfire-resort-dallas-fort-worth-planned/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('park-city','USA','Utah','http://www.skiresort.info/ski-resort/park-city/',3049);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('deer-valley','USA','Utah','http://www.skiresort.info/ski-resort/deer-valley/',2917);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowbird','USA','Utah','http://www.skiresort.info/ski-resort/snowbird/',3353);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alta','USA','Utah','http://www.skiresort.info/ski-resort/alta/',3215);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowbasin','USA','Utah','http://www.skiresort.info/ski-resort/snowbasin/',2850);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('solitude','USA','Utah','http://www.skiresort.info/ski-resort/solitude/',3000);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powder-mountain','USA','Utah','http://www.skiresort.info/ski-resort/powder-mountain/',2712);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('brighton','USA','Utah','http://www.skiresort.info/ski-resort/brighton/',3200);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sundance','USA','Utah','http://www.skiresort.info/ski-resort/sundance/',2515);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('brian-head','USA','Utah','http://www.skiresort.info/ski-resort/brian-head/',3328);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('eagle-point','USA','Utah','http://www.skiresort.info/ski-resort/eagle-point/',3230);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('beaver-mountain','USA','Utah','http://www.skiresort.info/ski-resort/beaver-mountain/',2700);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('nordic-valley','USA','Utah','http://www.skiresort.info/ski-resort/nordic-valley/',1930);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cherry-peak','USA','Utah','http://www.skiresort.info/ski-resort/cherry-peak/',2635);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('diamond-peaks','USA','Utah','http://www.skiresort.info/ski-resort/diamond-peaks/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powderbird','USA','Utah','http://www.skiresort.info/ski-resort/powderbird/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('whisper-ridge','USA','Utah','http://www.skiresort.info/ski-resort/whisper-ridge/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('stowe','USA','Vermont','http://www.skiresort.info/ski-resort/stowe/',1116);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('killington','USA','Vermont','http://www.skiresort.info/ski-resort/killington/',1285);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('okemo','USA','Vermont','http://www.skiresort.info/ski-resort/okemo/',1019);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('stratton','USA','Vermont','http://www.skiresort.info/ski-resort/stratton/',1181);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sugarbush','USA','Vermont','http://www.skiresort.info/ski-resort/sugarbush/',1240);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mount-snow','USA','Vermont','http://www.skiresort.info/ski-resort/mount-snow/',1095);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('jay-peak','USA','Vermont','http://www.skiresort.info/ski-resort/jay-peak/',1175);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mad-river-glen','USA','Vermont','http://www.skiresort.info/ski-resort/mad-river-glen/',1108);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('smugglers-notch','USA','Vermont','http://www.skiresort.info/ski-resort/smugglers-notch/',1112);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bromley-mountain','USA','Vermont','http://www.skiresort.info/ski-resort/bromley-mountain/',1001);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bolton-valley','USA','Vermont','http://www.skiresort.info/ski-resort/bolton-valley/',960);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pico-mountain','USA','Vermont','http://www.skiresort.info/ski-resort/pico-mountain/',1209);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('suicide-six','USA','Vermont','http://www.skiresort.info/ski-resort/suicide-six/',411);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('magic-mountain','USA','Vermont','http://www.skiresort.info/ski-resort/magic-mountain/',868);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('burke-mountain','USA','Vermont','http://www.skiresort.info/ski-resort/burke-mountain/',975);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('middlebury-college-snow-bowl','USA','Vermont','http://www.skiresort.info/ski-resort/middlebury-college-snow-bowl/',810);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('quechee-lakes-ski-area','USA','Vermont','http://www.skiresort.info/ski-resort/quechee-lakes-ski-area/',380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cochran-ski-area','USA','Vermont','http://www.skiresort.info/ski-resort/cochran-ski-area/',280);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('lyndon-outing-club','USA','Vermont','http://www.skiresort.info/ski-resort/lyndon-outing-club/',380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('northeast-slopes-east-corinth','USA','Vermont','http://www.skiresort.info/ski-resort/northeast-slopes-east-corinth/',355);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('living-memorial-park-brattleboro','USA','Vermont','http://www.skiresort.info/ski-resort/living-memorial-park-brattleboro/',189);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('aldis-hill-park-st-albans','USA','Vermont','http://www.skiresort.info/ski-resort/aldis-hill-park-st-albans/',150);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('haystack-mountain-the-hermitage-club','USA','Vermont','http://www.skiresort.info/ski-resort/haystack-mountain-the-hermitage-club/',975);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wintergreen-resort','USA','Virginia','http://www.skiresort.info/ski-resort/wintergreen-resort/',1071);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('massanutten','USA','Virginia','http://www.skiresort.info/ski-resort/massanutten/',871);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bryce-resort','USA','Virginia','http://www.skiresort.info/ski-resort/bryce-resort/',533);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-omni-homestead','USA','Virginia','http://www.skiresort.info/ski-resort/the-omni-homestead/',930);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cascade-powder-guides','USA','Washington','http://www.skiresort.info/ski-resort/cascade-powder-guides/',1705);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('crystal-mountain-wa','USA','Washington','http://www.skiresort.info/ski-resort/crystal-mountain-wa/',2137);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpental','USA','Washington','http://www.skiresort.info/ski-resort/alpental/',1670);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-summit-at-snoqualmie','USA','Washington','http://www.skiresort.info/ski-resort/the-summit-at-snoqualmie/',1180);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('stevens-pass','USA','Washington','http://www.skiresort.info/ski-resort/stevens-pass/',1750);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wenatchee-mission-ridge','USA','Washington','http://www.skiresort.info/ski-resort/wenatchee-mission-ridge/',2078);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('white-pass','USA','Washington','http://www.skiresort.info/ski-resort/white-pass/',1986);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-baker','USA','Washington','http://www.skiresort.info/ski-resort/mt-baker/',1525);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('49-degrees-north-mountain-resort','USA','Washington','http://www.skiresort.info/ski-resort/49-degrees-north-mountain-resort/',1760);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-spokane','USA','Washington','http://www.skiresort.info/ski-resort/mt-spokane/',1795);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('loup-loup-ski-bowl','USA','Washington','http://www.skiresort.info/ski-resort/loup-loup-ski-bowl/',1620);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bluewood','USA','Washington','http://www.skiresort.info/ski-resort/bluewood/',1730);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sitzmark','USA','Washington','http://www.skiresort.info/ski-resort/sitzmark/',1485);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hurricane-ridge','USA','Washington','http://www.skiresort.info/ski-resort/hurricane-ridge/',1676);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('echo-valley-lake-chelan','USA','Washington','http://www.skiresort.info/ski-resort/echo-valley-lake-chelan/',950);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('leavenworth-ski-hill','USA','Washington','http://www.skiresort.info/ski-resort/leavenworth-ski-hill/',520);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('badger-mountain','USA','Washington','http://www.skiresort.info/ski-resort/badger-mountain/',1158);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('meany-lodge','USA','Washington','http://www.skiresort.info/ski-resort/meany-lodge/',1027);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('north-cascade-heliskiing-mazama','USA','Washington','http://www.skiresort.info/ski-resort/north-cascade-heliskiing-mazama/',2700);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sahalie-ski-club','USA','Washington','http://www.skiresort.info/ski-resort/sahalie-ski-club/',966);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowshoe-mountain','USA','West Virginia','http://www.skiresort.info/ski-resort/snowshoe-mountain/',1478);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('timberline-four-seasons','USA','West Virginia','http://www.skiresort.info/ski-resort/timberline-four-seasons/',1301);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('winterplace','USA','West Virginia','http://www.skiresort.info/ski-resort/winterplace/',1097);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('canaan-valley','USA','West Virginia','http://www.skiresort.info/ski-resort/canaan-valley/',1304);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('oglebay-resort','USA','West Virginia','http://www.skiresort.info/ski-resort/oglebay-resort/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpine-meadows','USA','California','http://www.skiresort.info/ski-resort/alpine-meadows/',2632);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('heavenly','USA','California','http://www.skiresort.info/ski-resort/heavenly/',3060);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('northstar-california-resort','USA','California','http://www.skiresort.info/ski-resort/northstar-california-resort/',2624);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('squaw-valley','USA','California','http://www.skiresort.info/ski-resort/squaw-valley/',2760);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-rose','USA','Nevada','http://www.skiresort.info/ski-resort/mt-rose/',2957);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('kirkwood','USA','California','http://www.skiresort.info/ski-resort/kirkwood/',2987);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sugar-bowl','USA','California','http://www.skiresort.info/ski-resort/sugar-bowl/',2555);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sierra-at-tahoe','USA','California','http://www.skiresort.info/ski-resort/sierra-at-tahoe/',2698);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('diamond-peak','USA','Nevada','http://www.skiresort.info/ski-resort/diamond-peak/',2602);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('donner-ski-ranch','USA','California','http://www.skiresort.info/ski-resort/donner-ski-ranch/',2371);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('boreal','USA','California','http://www.skiresort.info/ski-resort/boreal/',2357);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('donner-ski-area','USA','California','http://www.skiresort.info/ski-resort/donner-ski-area/',2240);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('soda-springs','USA','California','http://www.skiresort.info/ski-resort/soda-springs/',2232);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('granlibakken','USA','California','http://www.skiresort.info/ski-resort/granlibakken/',2015);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('homewood-mountain-resort','USA','California','http://www.skiresort.info/ski-resort/homewood-mountain-resort/',2402);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('granite-peak-at-rib-mountain-state-park','USA','Wisconsin','http://www.skiresort.info/ski-resort/granite-peak-at-rib-mountain-state-park/',594);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('wilmot-mountain','USA','Wisconsin','http://www.skiresort.info/ski-resort/wilmot-mountain/',292);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('devils-head','USA','Wisconsin','http://www.skiresort.info/ski-resort/devils-head/',303);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-whitecap-mountains','USA','Wisconsin','http://www.skiresort.info/ski-resort/the-whitecap-mountains/',540);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('grand-geneva','USA','Wisconsin','http://www.skiresort.info/ski-resort/grand-geneva/',304);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-la-crosse','USA','Wisconsin','http://www.skiresort.info/ski-resort/mt-la-crosse/',372);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('trollhaugen','USA','Wisconsin','http://www.skiresort.info/ski-resort/trollhaugen/',362);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('alpine-valley-resort-elkhorn','USA','Wisconsin','http://www.skiresort.info/ski-resort/alpine-valley-resort-elkhorn/',415);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('christmas-mountain','USA','Wisconsin','http://www.skiresort.info/ski-resort/christmas-mountain/',370);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('tyrol-basin-mt-horeb','USA','Wisconsin','http://www.skiresort.info/ski-resort/tyrol-basin-mt-horeb/',344);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('little-switzerland-ski-resort','USA','Wisconsin','http://www.skiresort.info/ski-resort/little-switzerland-ski-resort/',380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('nordic-mountain','USA','Wisconsin','http://www.skiresort.info/ski-resort/nordic-mountain/',346);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sunburst','USA','Wisconsin','http://www.skiresort.info/ski-resort/sunburst/',357);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('the-rock-snow-park','USA','Wisconsin','http://www.skiresort.info/ski-resort/the-rock-snow-park/',270);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mont-du-lac','USA','Wisconsin','http://www.skiresort.info/ski-resort/mont-du-lac/',280);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('christie-mountain','USA','Wisconsin','http://www.skiresort.info/ski-resort/christie-mountain/',510);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('camp-10','USA','Wisconsin','http://www.skiresort.info/ski-resort/camp-10/',530);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('bruce-mound','USA','Wisconsin','http://www.skiresort.info/ski-resort/bruce-mound/',400);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('ausblick-sussex','USA','Wisconsin','http://www.skiresort.info/ski-resort/ausblick-sussex/',350);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('whitetail-ridge-fort-mccoy','USA','Wisconsin','http://www.skiresort.info/ski-resort/whitetail-ridge-fort-mccoy/',322);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('navarino-hills','USA','Wisconsin','http://www.skiresort.info/ski-resort/navarino-hills/',270);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('heiliger-huegel-hubertus','USA','Wisconsin','http://www.skiresort.info/ski-resort/heiliger-huegel-hubertus/',391);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('mt-ashwabay-salmo','USA','Wisconsin','http://www.skiresort.info/ski-resort/mt-ashwabay-salmo/',389);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('keyes-peak-florence','USA','Wisconsin','http://www.skiresort.info/ski-resort/keyes-peak-florence/',450);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('winter-park-kewaunee-county','USA','Wisconsin','http://www.skiresort.info/ski-resort/winter-park-kewaunee-county/',225);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('powers-bluff','USA','Wisconsin','http://www.skiresort.info/ski-resort/powers-bluff/',436);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('standing-rocks','USA','Wisconsin','http://www.skiresort.info/ski-resort/standing-rocks/',370);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('kettlebowl','USA','Wisconsin','http://www.skiresort.info/ski-resort/kettlebowl/',542);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('blackhawk-ski-club-middleton','USA','Wisconsin','http://www.skiresort.info/ski-resort/blackhawk-ski-club-middleton/',328);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('cascade-mountain','USA','Wisconsin','http://www.skiresort.info/ski-resort/cascade-mountain/',378);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('fox-hill','USA','Wisconsin','http://www.skiresort.info/ski-resort/fox-hill/',385);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('nutt-hill-plymouth','USA','Wisconsin','http://www.skiresort.info/ski-resort/nutt-hill-plymouth/',309);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('paul-bunyan-ski-hill','USA','Wisconsin','http://www.skiresort.info/ski-resort/paul-bunyan-ski-hill/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('potawatomi-park','USA','Wisconsin','http://www.skiresort.info/ski-resort/potawatomi-park/',0);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('skyline-friendship','USA','Wisconsin','http://www.skiresort.info/ski-resort/skyline-friendship/',392);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('triangle-sports-area-green-bay','USA','Wisconsin','http://www.skiresort.info/ski-resort/triangle-sports-area-green-bay/',217);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('jackson-hole','USA','Wyoming','http://www.skiresort.info/ski-resort/jackson-hole/',3185);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('grand-targhee','USA','Wyoming','http://www.skiresort.info/ski-resort/grand-targhee/',3048);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snow-king-mountain-jackson','USA','Wyoming','http://www.skiresort.info/ski-resort/snow-king-mountain-jackson/',2380);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('white-pine-pinedale','USA','Wyoming','http://www.skiresort.info/ski-resort/white-pine-pinedale/',2847);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('beartooth-basin','USA','Wyoming','http://www.skiresort.info/ski-resort/beartooth-basin/',3322);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('meadowlark-ski-lodge','USA','Wyoming','http://www.skiresort.info/ski-resort/meadowlark-ski-lodge/',2828);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('snowy-range','USA','Wyoming','http://www.skiresort.info/ski-resort/snowy-range/',2945);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('pine-creek','USA','Wyoming','http://www.skiresort.info/ski-resort/pine-creek/',2508);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('hogadon-ski-area','USA','Wyoming','http://www.skiresort.info/ski-resort/hogadon-ski-area/',2438);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('sleeping-giant','USA','Wyoming','http://www.skiresort.info/ski-resort/sleeping-giant/',2265);
INSERT INTO outdoors.skiing(Resort_Name,Country,State,URL,Altitude) VALUES ('antelope-butte','USA','Wyoming','http://www.skiresort.info/ski-resort/antelope-butte/',2865);
